export const INCREASE_SESSION = 'INCREASE_SESSION';
export const DECREASE_SESSION = 'DECREASE_SESSION';
export const INCREASE_BREAK = 'INCREASE_BREAK';
export const DECREASE_BREAK = 'DECREASE_BREAK';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
export const SET_IS_RESUME = 'SET_IS_RESUME';
export const SET_PLAY_TYPE = 'SET_PLAY_TYPE';
export const SET_TIMER = 'SET_TIMER';