const INCREASE_SESSION = 'INCREASE_SESSION';
const DECREASE_SESSION = 'DECREASE_SESSION';
const INCREASE_BREAK = 'INCREASE_BREAK';
const DECREASE_BREAK = 'DECREASE_BREAK';
const SET_TIMER = 'SET_TIMER';
const RESET = 'RESET';